spring:
  application:
    name: weather-api
  profiles:
    active: local
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/weather-api
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

services:
  visual-crossing:
    weather-api.url: https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline
    api-key: ${VISUAL_CROSSING_API_KEY}

api.weather.rate-limit: 5
auth.jwt.secret-key: ${JWT_SECRET_KEY}
