### GET current weather - malmö

GET http://localhost:8080/api/weather/malmo/current HTTP/1.1
Content-Type: application/json


### GET current weather - error

GET http://localhost:8080/api/weather/dhawjhdakwjhd/current HTTP/1.1
Content-Type: application/json


### POST login user

# @name login

POST http://localhost:8080/api/user/login HTTP/1.1
Content-Type: application/json

{
  "email": "something@email.com",
  "password": "verysecurepassword"
}


### POST subscribe location - malmö

POST http://localhost:8080/api/weather/kjugekull/subscribe HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}


### DELETE remove subscription

DELETE http://localhost:8080/api/weather/lund/subscribe HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}


### GET subscribed locations

GET http://localhost:8080/api/weather/locations/me HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}


### GET subscribed locations current weather

GET http://localhost:8080/api/weather/locations/current HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{login.response.body.token}}
